export {default as  Home} from './Home';
export {default as Error} from './Error';
// export{default as Dashboard} from './DashBoard/Dashboard.tsx'
export {default as DashBoard} from './DashBoard/Dashboard'
export {default as Community} from './Community'
export {default as Mentors} from './Mentors'
export {default as Sessions} from './Sessions'
export {default as Workshops} from './Workshops'
export {default as Timelines} from './Timeline'